name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore API.PerformanceTest
      run: dotnet restore IdiotBenchmark.API.PerformanceTest/IdiotBenchmark.API.PerformanceTest.csproj
    - name: Restore Dictionary.PerformanceTest
      run: dotnet restore IdiotBenchmark.Dictionary.PerformanceTest/IdiotBenchmark.Dictionary.PerformanceTest.csproj
    - name: Restore Mapper.PerformanceTest
      run: dotnet restore IdiotBenchmark.Mapper.PerformanceTest/IdiotBenchmark.Mapper.PerformanceTest.csproj
    - name: Restore String.PerformanceTest
      run: dotnet restore IdiotBenchmark.String.PerformanceTest/IdiotBenchmark.String.PerformanceTest.csproj
    - name: Build
      run: dotnet build
